### ISSUE TITLE
Brand image displays strangely on iOS 11 with XCode 9

### ISSUE THREAD

**Issue by jordansnyder** [particle-iot/particle-setup-ios#1]
<img width="417" alt="screen shot 2017-11-26 at 8 07 37 pm" src="https://user-images.githubusercontent.com/5607615/33249055-8a9e8546-d2e5-11e7-915d-9bc8a8ba4a59.png">
<img width="416" alt="screen shot 2017-11-26 at 8 07 52 pm" src="https://user-images.githubusercontent.com/5607615/33249054-8a90e36e-d2e5-11e7-99a4-cde9a7190f86.png">

**Comment by RaimundasSakalauskas** [comment]
This should now be fixed (together with recent layout refactor). If it is not, please reopen the issue.
