### ISSUE TITLE
Can't detect Photon SSID

### ISSUE THREAD

**Issue by andyhuber** [particle-iot/particle-setup-ios#6]
It seems like the SSID is never detected correctly, therefore it's not possible to connect a photon by the SDK: not sure that could be an iOS12 bug? 
the method "checkParticleDeviceWifiConnection" always return false. because the info dictionary is nil. is anyone having the same issues on iOS12?

**Comment by rickkas7** [comment]
Yes, you need to add the Access WiFi Information entitlement to your iOS app in iOS12:

https://community.particle.io/t/ios-12-softap-cant-connect-to-p1/44279/6

**Comment by andyhuber** [comment]
thanks I actually just figure it out :). Maybe it should be written somewhere in the Readme as well?
