### ISSUE TITLE
Important Updates to CNCopyCurrentnetworkInfo API in iOS 13

### ISSUE THREAD

**Issue by LordParsley** [particle-iot/particle-setup-ios#7]
The following email recently went out to Apple developers concerning new network privacy restrictions starting in iOS 13 which I believe will affect wifi setup in `checkParticleDeviceWifiConnection` and encourages migration to `NEHotSpotConfiguration` introduced in iOS 11.

https://github.com/particle-iot/particle-setup-ios/blob/c01471328ac1260d207f42b86fe0a6de608dd7a2/ParticleSetup/Comm/ParticleSetupCommManager.m#L128

> Dear Developer,

> As we announced at WWDC19, we're making changes to further protect user privacy and prevent unauthorized location tracking. Starting with iOS 13, the CNCopyCurrentNetworkInfo API will no longer return valid Wi-Fi SSID and BSSID information. Instead, the information returned by default will be:

> SSID: “Wi-Fi” or “WLAN” (“WLAN" will be returned for the China SKU)
BSSID: "00:00:00:00:00:00"

> If your app is using this API, we encourage you to adopt alternative approaches that don’t require Wi-Fi or network information. Valid SSID and BSSID information from CNCopyCurrentNetworkInfo will still be provided to VPN apps, apps that have used NEHotspotConfiguration to configure the current Wi-Fi network, and apps that have obtained permission to access user location through Location Services.

> Test your app on the latest iOS 13 beta to make sure it works properly. If your app requires valid Wi-Fi SSID and BSSID information to function, you can do the following:

> For accessory setup apps, use the NEHotSpotConfiguration API, which now has the option to pass a prefix of the SSID hotspot your app expects to connect to.
For other types of apps, use the CoreLocation API to request the user’s consent to access location information.

> Learn more by reading the updated documentation or viewing the the Advances in Networking session video from WWDC19. You can also submit a TSI for code-level support.

> Best regards,
> Apple Developer Relations

**Comment by RaimundasSakalauskas** [comment]
Hello, thank you for creating an issue. I have received the same email too and will look into this next week. As a quick workaround there's an option to request location permission. Will keep this thread updated with the progress.

**Comment by RaimundasSakalauskas** [comment]
Latest release (https://github.com/particle-iot/particle-setup-ios/releases/tag/0.9.1) addresses the issue. If iOS 13 is detected, user is presented with a screen explaining why we need location permission to advance. Please also note that you will need to provide `Privacy - Location When In Use Usage Description` in info.plist.

**Comment by LordParsley** [comment]
Thanks very much for addressing that @RaimundasSakalauskas 👍

Are there any plans to move to `NEHotspotConfiguration` ? From my understanding it
* Doesn't require the user to leave the app at all, making the setup process much simpler for our users,
* Is available from iOS 11, which actually includes our whole user base at present, and
* Seems to be fairly simple to implement from a code perpective using `joinOnce` if the SSID is known? ref https://developer.apple.com/documentation/networkextension/nehotspotconfiguration/2887518-joinonce?language=objc & https://stackoverflow.com/a/46078618/1277350

**Comment by RaimundasSakalauskas** [comment]
I am the loudest ambassador of us switching to `NEHotspotConfiguration`, however to do that, we need to change both - our manufacturing process and setup process. That API requires us to know exact SSID beforehand, which app does not right now. I am trying to figure out if it's possible to get SSID if user scans serial number barcode located on the box. Even if that is possible, current gen of Photons don't have serial numbers on them (only on the box), so unless SN is added on the hardware in the future, current setup process would still have to be there for all existing photons.

**Comment by LordParsley** [comment]
Thanks very much for explaining @RaimundasSakalauskas 👍

I see what you mean, the prefix is configurable but the exact SSID isn't necessarily known:
https://github.com/particle-iot/particle-setup-ios/blob/c01471328ac1260d207f42b86fe0a6de608dd7a2/ParticleSetup/Comm/ParticleSetupCommManager.m#L136

Much appreciated!
